
Vagrant.configure("2") do |config|

  config.vm.define "hrecoletS" do |server|

    server.vm.hostname = "hrecoletS"
    server.vm.box = "debian/bookworm64"

    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.cpus = "1"
    end


    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt install curl -y
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none --token 12345
      
      # install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl
    
    SHELL
  end

  config.vm.define "hrecoletSW" do |worker|

    worker.vm.hostname = "hrecoletSW"
    worker.vm.box = "debian/bookworm64"

    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.cpus = "1"
    end


    worker.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt install curl -y
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110 --token 12345" sh -s -
      
      # install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl

      SHELL
  end
end
