apiVersion: apps/v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
    - name: nginx
      image: nginx:latest
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
    - name: nginx
      image: nginx:latest
  
