# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
     libvirt.memory = "1024"
     libvirt.cpus = "1"
  end

  config.vm.define "hrecoletS" do |server|
    server.vm.box = "debian/bookworm64" 
    server.vm.hostname = "hrecoletS"

    #Network
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provision "shell", path: "server.sh"
    config.vm.provision "file", source: "k3s-manifest.yaml", destination: "~/"
  end
end
