apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  labels:
    app: app
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: config
    repoURL: 'https://github.com/hugorclt/argocd-hrecolet.git'
    targetRevision: HEAD
  project: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
