# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "hrecoletS" do |server|
    # Operating system
    server.vm.box = "debian/bookworm64"

    # Ressource
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    #Network
    server.vm.network "public_network", ip: "192.168.56.110"

    # Installing dependencies "provisionning"
    server.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install curl -y
      
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh - --token 12345 

      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl
    SHELL
  end


  config.vm.define "hrecoletSW" do |worker|
    # Operatin system
    worker.vm.box = "debian/bookworm64"

    # Ressource
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    #Network
    worker.vm.network "public_network", ip: "192.168.56.111"

    # Installing dependencies "provisionning"
    worker.vm.provision "shell", inline: "apt update"
    worker.vm.provision "shell", inline: "apt install curl -y"
    worker.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=12345 sh -s -"
  end
end
