# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "hrecoletS" do |server|
    # Operating system
    server.vm.box = "debian/bookworm64"

    # Ressource
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = "1024"
      libvirt.cpus = "1"
    end

    #Network
    server.vm.network "private_network", ip: "192.168.56.110"

    # Installing dependencies "provisionning"
    server.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install curl -y
	  apt install net-tools -y

	# K3s install
	  echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/vagrant/.profile
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 K3S_TOKEN=12345 K3S_CLUSTER_INIT=1 INSTALL_K3S_EXEC="--tls-san https://192.168.56.110:6443" sh -

	# Kubectl install
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl
    SHELL
  end

  config.vm.define "hrecoletSW" do |worker|
    # Operatin system
    worker.vm.box = "debian/bookworm64"

    # Ressource
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = "1024"
      libvirt.cpus = "1"
    end

    #Network
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Installing dependencies "provisionning"
    worker.vm.provision "shell", inline: "apt update"
    worker.vm.provision "shell", inline: "apt install curl -y"

    worker.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='agent --server https://192.168.56.110:6443 --token 12345' sh -s -"
  end

end
