apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: 8888-8888
    nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: app
  type: NodePort

      #---
      #apiVersion: networking.k8s.io/v1
      #kind: Ingress
      #metadata:
      #  name: app-ingress
      #  annotations:
      #    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
# rules:
#   - http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: app
#               port:
#                 number: 8888
